# Generated by Django 3.0.6 on 2020-06-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-last_modified'], 'permissions': (('can_view_all_questions', 'Can view all questions'),)},
        ),
    ]
